- name: Configure Hashicorp Vault with DynamoDB backend and TLS
  hosts: hashivaultserver
  become: true
  environment:
    VAULT_ADDR: "https://{{ vault_listen_address }}"
  tasks:
    - name: Install Unzip Package
      apt:
        name: unzip
        state: present

    - name: Download AWS CLI Package
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "/home/{{ ansible_user }}/"

    - name: Unzip AWS CLI Package
      unarchive:
        src: awscli-exe-linux-x86_64.zip
        dest: "/home/{{ ansible_user }}/"
        remote_src: yes
    
    - name: Run installation script
      command: ./aws/install --update

    - name: Setup Hashicorp GPG key
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install HashiCorp Vault
      apt:
        name: vault
        state: present

    - name: Create confidential directory
      file:
        path: "/home/{{ ansible_user }}/.confidential"
        state: directory

    - name: Retrieve TLS cert
      shell: aws secretsmanager get-secret-value --secret-id {{ vault_tls_cert_secret_id }} --query 'SecretBinary' | sed 's/"//g' | base64 --decode > {{ vault_tls_cert_file }}

    - name: Retrieve TLS key
      shell: aws secretsmanager get-secret-value --secret-id {{ vault_tls_key_secret_id }} --query 'SecretBinary' | sed 's/"//g' | base64 --decode > {{ vault_tls_key_file }}

    - name: Configure Vault Server
      template:
        src: ./templates/hashivault.hcl.j2
        dest: "{{ vault_config_dir }}/hashivault.hcl"

    - name: Start Vault Server
      command: "vault server -config={{ vault_config_dir }}/hashivault.hcl"
      async: 360000
      poll: 0
      # environment:
      #   VAULT_ADDR: "https://{{ vault_listen_address }}"

    - name: Wait for Vault to Start
      wait_for:
        port: 8200
        delay: 5
        timeout: 300

    - name: Initialize Vault
      command: "vault operator init"
      register: vault_init

    - name: Display Vault Unseal Keys and Root Token
      debug:
        var: vault_init.stdout_lines
      ignore_errors: true

    - name: Store Vault Unseal Keys and Root Token in a Secure Location
      copy:
        content: "{{ vault_init.stdout_lines | join('\n') }}"
        dest: "/home/{{ ansible_user }}/.confidential/vault_init.txt"
        mode: '444'

    - name: Unseal Vault
      command: "vault operator unseal {{ item | regex_search('(?<=:\\s).*') }}"
      loop: "{{ vault_init.stdout_lines[:3] }}"

    - name: Login Vault
      command: "vault login {{ vault_init.stdout_lines[6] | regex_search('(?<=:\\s).*') }}"

    - name: Configure Vault Storage Backend
      command: "vault secrets enable -path=secret kv"

    - name: Enable DynamoDB as Storage Backend
      command: "vault secrets enable -path=dynamodb database"
